import AppKit
import SwiftUI

struct ClipboardEntry: Identifiable, Equatable {
    let id = UUID()
    let text: String
    let date: Date

    /// Una sola línea para la lista: los pegados suelen traer saltos y sangrías que
    /// romperían la altura de fila.
    var preview: String {
        text.split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: " ")
    }

    var lineCount: Int {
        text.split(whereSeparator: \.isNewline).count
    }
}

/// Historial de las últimas copias de texto.
///
/// **No se guarda en disco a propósito.** Por el portapapeles pasan contraseñas, tokens
/// y datos bancarios; persistirlos en `UserDefaults` los dejaría en texto plano dentro
/// del contenedor de la app. El historial vive sólo en memoria y muere con la sesión.
@MainActor
final class ClipboardStore: ObservableObject {

    @Published private(set) var entries: [ClipboardEntry] = []

    static let capacity = 5

    /// Convención de nspasteboard.com: los gestores de contraseñas marcan así lo que
    /// nadie debería historizar. Respetarlo es la diferencia entre una herramienta y
    /// una fuga de credenciales.
    private static let skippedTypes: [NSPasteboard.PasteboardType] = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ].map(NSPasteboard.PasteboardType.init(rawValue:))

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    private static let pollInterval: TimeInterval = 0.6

    // MARK: - Ciclo de vida

    func start() {
        guard timer == nil else { return }

        timer = Timer.repeatingOnCommonModes(every: Self.pollInterval) { [weak self] in
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // MARK: - Captura

    /// `NSPasteboard` no emite notificaciones: sondear `changeCount` es la única vía.
    /// Es barato — un entero — así que 0.6 s no se nota.
    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        guard !types.contains(where: Self.skippedTypes.contains) else { return }

        guard let text = pasteboard.string(forType: .string) else { return }
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        guard entries.first?.text != text else { return }

        withAnimation(DockMetrics.moduleAnimation) {
            // Si ya estaba en la lista, sube al principio en vez de duplicarse.
            entries.removeAll { $0.text == text }
            entries.insert(ClipboardEntry(text: text, date: Date()), at: 0)

            if entries.count > Self.capacity {
                entries.removeLast(entries.count - Self.capacity)
            }
        }
    }

    // MARK: - Acciones

    func copy(_ entry: ClipboardEntry) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(entry.text, forType: .string)

        // Adoptamos el nuevo `changeCount` para que el sondeo no vuelva a registrar
        // lo que acabamos de escribir nosotros.
        lastChangeCount = pasteboard.changeCount

        withAnimation(DockMetrics.moduleAnimation) {
            entries.removeAll { $0.id == entry.id }
            entries.insert(entry, at: 0)
        }
    }

    func remove(_ entry: ClipboardEntry) {
        withAnimation(DockMetrics.moduleAnimation) {
            entries.removeAll { $0.id == entry.id }
        }
    }

    func clear() {
        withAnimation(DockMetrics.moduleAnimation) { entries.removeAll() }
    }
}
